apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
  namespace: default
  labels:
    app: pipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - name: pipeline
        image: naitikag/pipestream:latest
        ports:
        - containerPort: 8000
